services:
  web:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
    - ./frontend:/app
    - /app/node_modules
    environment:
      - PORT=3000
    env_file:
      - .env

  backend:
    build: backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - PORT=4000
    env_file:
      - .env

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql


volumes:
  pgdata:
